### ISSUE TITLE
Unclear if allows hierarchy (recursion)

### ISSUE THREAD

**Issue by PhilipEardley** [oscargdd/l3nm#11]
It's unclear if the document allows more than two levels. ie the document discusses the scenario with end-to-end L3VPN delivered by a 'stringing together' a series of VPNs across the underlying domains ("multi domain"). But what happens if one of those VPNs is actually delivered in turn by underlying networks? ("multiple levels of hierarchy") 
I believe this is likely - because, for example, there'll be operators that specialise in different geographic areas, different technologies, for commercial and regulatory reasons. Imagine a global service provider that buys network service in the UK from operator X, but operator X in turn buys network service from other operators (perhaps they have a better network in city A, or a particular QoS technology that the service requires etc).
The general point is that the number of levels in the hierarchy is not known.

Do the approaches in the draft need to be modified?

**Comment by oscargdd** [comment]
Complex scenarios with VPNs Split across multiple VPNs are dealt in composed-vpn draft. Current draft allows hierarchy inside an operators network (internal administrative domains)
