### ISSUE TITLE
Site-bearer issue

### ISSUE THREAD

**Issue by sunseawq** [oscargdd/l3nm#12]
Not sure how site-bearer is related to bearer under each site-network-access? Allow bearer-reference to leafref bearer-id under site-bearer? 
Why not consolidate them into one? Add site-bearer again add software development cost to associate bearer-id under site-bearer with bearer under each site-network-access? No?

**Comment by oscargdd** [comment]
Hi! The original idea was to have under site the list of bearers for "inventory" purposes, to be able to know which are the phisical connections between the custormers and the network. That implies a two step process, first of all, the list of bearers have to be added, and in a second step, when creating a site network Access, identify which bear to use. 
We could simplify, and, under site-network-access just identify the NE and port. 
Thoughts?

**Comment by sunseawq** [comment]
Thanks for response. I support to do simplification. combining them into one step will save cost and reduce complexity.

**Comment by sbarguil** [comment]
One of the things I guess Is important to add is: the site bearer restricts the possibility to start services from any point of the network to any point of the network. Once you select a site, you can only select the bearers you have "connected" to that site to start the service. This can be helpfull to support the right service provision.

**Comment by sbarguil** [comment]
Our idea is kept the bearer until the draft became a Working Group Document, After that the idea is to socialize this discussion in the mailing list.

**Comment by sbarguil** [comment]
Please use issue #15 for discussion
