### ISSUE TITLE
Hierarchy: SIte & Bearer Removal

### ISSUE THREAD

**Issue by sbarguil** [oscargdd/l3nm#15]
It is possible to change the "Site Centric" definition of the L3SM and use a new "VRF Centric" approach. For that reason Site and Bearer Containers should be removed. 

It groups the discussion related to issue #12 and #13.

**Comment by oscargdd** [comment]
The bearer_id has been preserved. Site has been removed. Now the model is not centered on site, but on the new concept of "vpn_nodes"

**Comment by oscargdd** [comment]
Fixed in -01 version
