### ISSUE TITLE
IE profiles vs RT-RD under vpn nodes

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/l3nm#3]
In versión -01 the main idea of the IE-Profiles container is re use the profiles between nodes that belong to the same L3VPN. For example, In the case you want to include five nodes in the same L3VPN you don't need to add the [RD,RTs] data to each VPN-Node; Whit this container the [RT,RD] data is created once and you can reuse it in the five VPN-Nodes.  However, there are cases where RTs could be same for all VPN-nodes, but RD have to be different for each VPN-Node, i.e., each VPN-Node have different RD, in this case, the strength of IE-profile can not be exerted. 
That’s why Qin suggests to consolidate RD,RT pairs within IE-profile into VPN node.

**Comment by sbarguil** [comment]
This is the current solution proposed:

Maintain the IE Profiles:

   |     +--rw ie-profiles
     |     |  +--rw ie-profile* [ie-profile-id]
     |     |     +--rw ie-profile-id    string
     |     |     +--rw rd?              rt-types:route-distinguisher
     |     |     +--rw vpn-targets
     |     |        +--rw vpn-target* [route-target]
     |     |           +--rw route-target         rt-types:route-target
     |     |           +--rw route-target-type    rt-types:route-target-type


However, put the RD/RT as optional under the VPN Service:

     |     +--rw vpn-nodes
     |     |  +--rw vpn-node* [vpn-node-id ne-id]
     |     |     +--rw vpn-node-id        string
     |     |     +--rw description?       string
     |     |     +--rw ne-id              string
     |     |     +--rw router-id?         inet:ipv4-address
     |     |     +--rw node-role?         identityref
     |     |     +--rw rd?                rt-types:route-distinguisher
     |     |     +--rw vpn-targets
     |     |     |  +--rw vpn-target* [route-target]
     |     |     |     +--rw route-target         rt-types:route-target
     |     |     |     +--rw route-target-type    rt-types:route-target-type
