### ISSUE TITLE
introduce access group level between site level and network access level

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/l3nm#6]
3rd comment of Qin in OPSAWG mailing list

Group-id defined in site level and site-network-access level become useless, since it is used in L3SM model as access constraints parameters to select PE, in L3NM model, PE has already been selected. 
However in L3NM model, we still want to classify the network access associated with the VPN service into several groups and want to know which network accesses associated with the same VPN belong to which group, e.g., when one site connect to two VPN, this site has three network accesses, let’s say access A, Access B, Access C
Access A, Access B connect to VPN A, Access C connect to VPN B, we can classify them into two group, Access A and Access B belong to dual home group, Access C belong to single home group.
Suggest change is to introduce access group level between site level and network access level, looks like this:
     +--rw sites
        +--rw site* [site-id]
           +--rw site-id                  svc-id
           +--rw access-groups
              +--rw access-group* [group-id]
                 +--rw group-id      svc-id
                 +--rw site-network-accesses
                     +--rw site-network-access* [site-network-access-id]
                         +--rw site-network-access-id      svc-id
                         +  vpn-node
                         +--rw bearer
                         |  +--…
                         +--rw availability

**Comment by sbarguil** [comment]
added as follows:

+--rw site-network-accesses
  +--rw site-network-access* [site-network-access-id]
    +--rw access-group-id?            yang:uuid
