### ISSUE TITLE
Clarify and review tag types 

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/l3nm#7]
5th comment of Qin in OPSAWG mailing list.

Regarding  tg-type and  cvlan-id under dot1q-vlan-tagged, it is not clear we should define multiple tag types, what is the real use case ? Also usually one interface will be configured with multiple cvlan-ids, how to deal with it?

The definitions were brought from L2SM, hence a review is need for next version

**Comment by sbarguil** [comment]
The model of connection has been pruned:

                 |  +--rw connection
                 |  |  +--rw encapsulation-type?   identityref
                 |  |  +--rw tagged-interface
                 |  |     +--rw type?                identityref
                 |  |     +--rw dot1q-vlan-tagged {dot1q}?
                 |  |     |  +--rw tg-type?    identityref
                 |  |     |  +--rw cvlan-id    uint16
                 |  |     +--rw priority-tagged
                 |  |     |  +--rw tag-type?   identityref
                 |  |     +--rw qinq {qinq}?
                 |  |     |  +--rw tag-type?   identityref
                 |  |     |  +--rw svlan-id    uint16
                 |  |     |  +--rw cvlan-id    uint16
                 |  |     +--rw qinany {qinany}?
                 |  |     |  +--rw tag-type?   identityref
                 |  |     |  +--rw svlan-id    uint16
                 |  |     +--rw vxlan {vxlan}?
                 |  |        +--rw vni-id       uint32
                 |  |        +--rw peer-mode?   identityref
                 |  |        +--rw peer-list* [peer-ip]
                 |  |           +--rw peer-ip    inet:ip-address
