### ISSUE TITLE
site attachment issue

### ISSUE THREAD

**Issue by sunseawq** [oscargdd/l3nm#8]
Each site_network_access will represent an interface on PE, we should make sure each network access is only assigned with one single VPN nodes, and at the same we can allow Each VPN node have multiple site-network-accesses.
In the current model, this is not clear:
     |     +--rw vpn-nodes
     |     |  +--rw vpn-node* [vpn-node-id ne-id]
     |     |     +--rw vpn-node-id         string
……
     |     |     +--rw site-attachments
     |     |        +--rw site-attachment* [site-id]
     |     |           +--rw site-id                   -> /l3vpn-ntw/sites/site/site-id
     |     |           +--rw site-network-access-id*   -> /l3vpn-ntw/sites/site/site-network-accesses/site-network-access/site-network-access-id
unless you add constraint to restrict one site-network-access-id only having one vpn node. Simply way to address this is to delete site-attachments, and add vpn-attachment as follows:
             +--rw site-network-accesses
                +--rw site-network-access* [site-network-access-id]
                   +--rw site-network-access-id      svc-id
                   +--rw site-network-access-type?   identityref
                   +--rw vpn-attachment
                      +--rw vpn-node-id              string
In this case, we don’t need to associate site-id together with site-network-access-id with one VPN node.
Another benefit is to make it easy to map L3NM to Network instance model in RFC8529, which establish one to one relationship between interface and network instance.

**Comment by sunseawq** [comment]
Another alternative way is to introduce vpn-node-id under each site-network-access, where vpn-node-id leafref the vpn-node defined under vpn-nodes container.

**Comment by alexaguado** [comment]
The original purpose was to separate anything related to VRF and parameters related to the connectivity of the client, so that is why we moved the relation there. Logically speaking, I liked the original approach, although I agree that yours is a more practical approach, so I personally agree on this modification.

Shall we wait for others input or proceed @oscargdd @sbarguil ?

A clarification to the first line you commented: "Each site_network_access will represent an interface on PE", I would say more than "Each site_network_access is linked to one (and only one) interface on PE", but a single interface may carry multiple VLANs, each of them defined at a different site-network-access (and, potentially, associated to a different service). Does this make sense?

**Comment by sunseawq** [comment]
Thanks, Alejandro. If we see site_network_access as sub-interface and allow one interface have multiple sub-interface, we may still allow one sub-interface being configured with multiple VLANs, how do we model this?

**Comment by alexaguado** [comment]
I would say that it is not supported by the current implementation of the model. We did not see the need for implementing this, based on the services we analysed so far at that time. To me, it seems more suitable for L2 services (pure switching), but still, if you have this use case being requested by other operators or provide some examples, it could be addressed in the next version.

**Comment by sbarguil** [comment]
@sunseawq and @alexaguado as far we have seen in the network this sub-interface multiple vlan scenario is not used under the l3vpn scenario. 
However I fully agree with @sunseawq and I believe that add the VPN-attachement under the VPN node is a very good approach to achieve the rigth cardinality between the VPN Node and the SNA.

**Comment by alexaguado** [comment]
Lets take the action then and do the change the reference from the VPN node to the SNA.
@sbarguil can you address this?

**Comment by sunseawq** [comment]
@alexaguado @sbarguil Thanks for addressing this. Let's leave aside sub-interface multiple vlan scenario 
 for now.

**Comment by sbarguil** [comment]
+--rw vpn-attachment
                    +--rw node-id?      -> /l3vpn-ntw/vpn-services/vpn-nodes/vpn-node/vpn-node-id
                    +--rw service-id?   -> /l3vpn-ntw/vpn-services/vpn-service/vpn-id

This is the current solution proposed.

**Comment by sunseawq** [comment]
The proposed change looks good, thanks.

**Comment by alexaguado** [comment]
Looks good to me as well. Thanks @sbarguil @sunseawq

**Comment by sunseawq** [comment]
Just want to confirm, so we still allow one site  have multiple network access and each network access can belong to different VPN.

**Comment by sbarguil** [comment]
@sunseawq sorry the delay. Yes!

**Comment by sunseawq** [comment]
Thanks, when can we make v-02 ready?

**Comment by sbarguil** [comment]
I'm finishing small changes. Tomorrow I'll do the commit. So it would be available.

**Comment by sunseawq** [comment]
Any update on this? Have a second thought, would it be good to move service-id under vpn-attachment to be the parameter under each site. This will help group all network accessess beloning to the same VPN which will save a lot of softeware development cost.

**Comment by sbarguil** [comment]
@sunseawq The new realease was updated yesterday using both service-id and node-id:
+--rw vpn-attachment
+--rw node-id? -> /l3vpn-ntw/vpn-services/vpn-nodes/vpn-node/vpn-node-id
+--rw service-id? -> /l3vpn-ntw/vpn-services/vpn-service/vpn-id

**Comment by sunseawq** [comment]
I have seen v-02 of draft-aguado-opsawg-l3sm-l3nm. Can you point me the link?

**Comment by sbarguil** [comment]
Sorry @sunseawq I was wrong. I have uploaded the model to the git but Oscar has not uploaded the draft yet. My mistake!

I hope he upload it asap (between today and tomorrow)

**Comment by sbarguil** [comment]
container removed:

+--rw site-network-accesses
  +--rw site-network-access* [site-network-access-id]
    +--rw node-id?                    -> /l3vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-node-id
    +--rw service-id?                 -> /l3vpn-ntw/vpn-services/vpn-service/vpn-id
